services:

  postgres:
    image: postgres:15
    container_name: todo-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11111
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: todo-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:11111@postgres:5432/tododb

volumes:
  postgres_data: